export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const COURSE_ROUTE = '/course'
export const USER_ROUTE = '/user'